version: '3.3'

services:
    image_diff_server:
        build: image
        ports:
            - "3000:3000"
        volumes:
           - image_data_volume:/imageDiffServer/data
           - image_data_volume:/imageDiffServer/public/images

volumes:
    image_data_volume: